export enum ActionTypes {
  LOG_IN = "log_in",
  LOG_OUT = "log_out",
  SIGN_UP = "sign_up",
  LOADING_USER = "loading_user",
  MESSAGE_RECIEVED = "message_recieved",
  SET_USER_ERROR = "set_user_error",
  GET_USER = "get_user",
  GET_FRIENDS = "get_friends",
  GET_FRIEND = "get_friend",
  LOADING_FRIEND = "loading_friend",
  ADD_FRIEND = "add_friend",
  SEND_FRIEND_REQUEST = "send_friend_request",
  GET_MESSAGES = "get_messages",
  SET_DUMMY_MESSAGES = "set_dummy_messages",
  SEND_MESSAGE = "send_message",
  MESSAGE_SENT = "message_sent",
  RESET_FETCH_MESSAGE = "reset_fetch_message",
  GET_FRIEND_REQUESTS = "get_friend_requests",
  ACCEPT_FRIEND_REQUEST = "accept_friend_request",
  DENY_FRIEND_REQUEST = "deny_friend_request",
}
